# Generated by Django 3.2.5 on 2026-04-13 20:26

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color_hex', models.CharField(default='#39A900', max_length=7, validators=[inventario.models.validar_color_hex])),
                ('descripcion', models.TextField(blank=True)),
                ('permite_prestamo', models.BooleanField(default=True)),
                ('es_critico', models.BooleanField(default=False)),
                ('prioridad', models.IntegerField(default=1)),
                ('abreviatura', models.CharField(blank=True, max_length=5, null=True)),
                ('requiere_mantenimiento', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('visible_en_reportes', models.BooleanField(default=True)),
                ('icon_name', models.CharField(default='check-circle', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('piso', models.IntegerField(default=1)),
                ('tipo', models.CharField(choices=[('BOD', 'Bodega'), ('LAB', 'Laboratorio'), ('OFI', 'Oficina'), ('SAL', 'Sala de Sistemas')], default='OFI', max_length=3)),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('es_externa', models.BooleanField(default=False)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
