# Generated by Django 3.2.5 on 2026-04-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20260413_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado del Activo', 'verbose_name_plural': 'Estados de los Activos'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_compra', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='activos/%Y/%m/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_categoria', to='inventario.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_estado', to='inventario.estado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_ubicacion', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Activo Tecnológico',
                'verbose_name_plural': 'Activos Tecnológicos',
            },
        ),
    ]
