# Generated by Django 3.2.5 on 2026-04-13 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_auto_20260413_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='activo',
            new_name='estado_activo',
        ),
        migrations.AlterField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PREV', 'Preventivo'), ('CORR', 'Correctivo'), ('GAR', 'Garantía')], max_length=4)),
                ('tecnico_responsable', models.CharField(max_length=150)),
                ('descripcion_problema', models.TextField()),
                ('tareas_realizadas', models.TextField(blank=True)),
                ('repuestos_cambiados', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('adjunto_reporte', models.FileField(blank=True, null=True, upload_to='mantenimientos/pdfs/')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.activo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='inventario.activo')),
                ('ubicacion_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='inventario.ubicacion')),
                ('ubicacion_nueva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='inventario.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
            },
        ),
    ]
