# Generated by Django 4.1.13 on 2026-04-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20260413_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='imagen',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='estado',
            new_name='activa',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='estado_activo',
            new_name='activa',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='precio',
        ),
        migrations.AddField(
            model_name='activo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='valor_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.estado'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion'),
        ),
    ]
