# Generated by Django 4.1.13 on 2026-04-13 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(help_text='Nombre del usuario (guardado para histórico)', max_length=150)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar')], max_length=20)),
                ('modelo', models.CharField(help_text='Nombre del modelo afectado (ej: Activo, Categoria)', max_length=100)),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=100, null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Representación del objeto', max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la acción')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado antes del cambio (JSON)', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado después del cambio (JSON)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Navegador y sistema operativo', max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-fecha_hora'], name='inventario__fecha_h_ccf3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='inventario__usuario_441826_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['modelo', '-fecha_hora'], name='inventario__modelo_cff00b_idx'),
        ),
    ]
