"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.db.backends.base.base import BaseDatabaseWrapper
BaseDatabaseWrapper.check_database_version_supported = lambda x: None

# Fix para MariaDB 10.4 (evitar error RETURNING)
from django.db.backends.mysql.base import DatabaseWrapper
DatabaseWrapper.features_class.can_return_columns_from_insert = False
DatabaseWrapper.features_class.can_return_rows_from_bulk_insert = False

# BASE DEL PROYECTO
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SEGURIDAD (DESARROLLO)
# =========================
SECRET_KEY = 'django-insecure-inventario-sena-2026'

DEBUG = True

ALLOWED_HOSTS = ['*']


# =========================
# APLICACIONES INSTALADAS
# =========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 👇 TU APP (IMPORTANTE CON AppConfig)
    'inventario.apps.InventarioConfig',

    # =========================================
    # DJANGO REST FRAMEWORK Y UTILIDADES
    # =========================================
    'rest_framework',           # ← API REST
    'django_filters',           # ← Filtros para la API
    'drf_yasg',                 # ← Documentación Swagger
]


# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


# =========================
# PLANTILLAS
# =========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# =========================
# BASE DE DATOS (MySQL / MariaDB)
# =========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'inventario_tech_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# =========================
# VALIDACIÓN DE CONTRASEÑAS
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================
# INTERNACIONALIZACIÓN
# =========================
LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# =========================
# ARCHIVOS ESTÁTICOS
# =========================
STATIC_URL = '/static/'


# =========================
# ARCHIVOS MEDIA (IMÁGENES)
# =========================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# =========================
# PRIMARY KEY
# =========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================
# CONFIGURACIÓN DE LOGIN
# =========================
LOGIN_URL = 'inventario:login'
LOGIN_REDIRECT_URL = 'inventario:dashboard'
LOGOUT_REDIRECT_URL = 'inventario:login'


# =========================================
# DJANGO REST FRAMEWORK CONFIGURATION
# =========================================

REST_FRAMEWORK = {
    # =====================================
    # AUTENTICACIÓN
    # =====================================
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    
    # =====================================
    # PERMISOS GLOBALES
    # =====================================
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # =====================================
    # FILTROS Y BÚSQUEDA
    # =====================================
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # =====================================
    # PAGINACIÓN
    # =====================================
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}